microgames-user-service:
  build: ./user_service
  ports:
    - 9092:9091
  environment:
    MICRO_SERVER_ADDRESS: ":9091"
    MICRO_REGISTRY: "mdns"


microgames-micro-api:
  image: gharsallahmoez/micro:latest
  environment:
    MICRO_REGISTRY: "mdns"
  links:
    - microgames-user-service
  ports:
    - 8080:8080
  command: api --handler=rpc --namespace=microgames.service