// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package test

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Info1 struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info1) Reset()         { *m = Info1{} }
func (m *Info1) String() string { return proto.CompactTextString(m) }
func (*Info1) ProtoMessage()    {}
func (*Info1) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *Info1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info1.Unmarshal(m, b)
}
func (m *Info1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info1.Marshal(b, m, deterministic)
}
func (m *Info1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info1.Merge(m, src)
}
func (m *Info1) XXX_Size() int {
	return xxx_messageInfo_Info1.Size(m)
}
func (m *Info1) XXX_DiscardUnknown() {
	xxx_messageInfo_Info1.DiscardUnknown(m)
}

var xxx_messageInfo_Info1 proto.InternalMessageInfo

func (m *Info1) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Info2 struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info2) Reset()         { *m = Info2{} }
func (m *Info2) String() string { return proto.CompactTextString(m) }
func (*Info2) ProtoMessage()    {}
func (*Info2) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *Info2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info2.Unmarshal(m, b)
}
func (m *Info2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info2.Marshal(b, m, deterministic)
}
func (m *Info2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info2.Merge(m, src)
}
func (m *Info2) XXX_Size() int {
	return xxx_messageInfo_Info2.Size(m)
}
func (m *Info2) XXX_DiscardUnknown() {
	xxx_messageInfo_Info2.DiscardUnknown(m)
}

var xxx_messageInfo_Info2 proto.InternalMessageInfo

func (m *Info2) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Info3 struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info3) Reset()         { *m = Info3{} }
func (m *Info3) String() string { return proto.CompactTextString(m) }
func (*Info3) ProtoMessage()    {}
func (*Info3) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{2}
}

func (m *Info3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info3.Unmarshal(m, b)
}
func (m *Info3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info3.Marshal(b, m, deterministic)
}
func (m *Info3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info3.Merge(m, src)
}
func (m *Info3) XXX_Size() int {
	return xxx_messageInfo_Info3.Size(m)
}
func (m *Info3) XXX_DiscardUnknown() {
	xxx_messageInfo_Info3.DiscardUnknown(m)
}

var xxx_messageInfo_Info3 proto.InternalMessageInfo

func (m *Info3) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Info1)(nil), "test.info1")
	proto.RegisterType((*Info2)(nil), "test.info2")
	proto.RegisterType((*Info3)(nil), "test.info3")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 78 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xc4, 0xb9, 0x58, 0x33, 0xf3,
	0xd2, 0xf2, 0x0d, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83,
	0x98, 0x32, 0x53, 0x60, 0x12, 0x46, 0xb8, 0x24, 0x8c, 0xd1, 0x25, 0x92, 0xd8, 0xc0, 0xe6, 0x1a,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xac, 0x1d, 0x22, 0xde, 0x65, 0x00, 0x00, 0x00,
}
